[book]
authors = ["Morg", "Sakubi", "duykhanh471"]
language = "vi"
src = "src"
title = "Yokubi - Tự học ngữ pháp Tiếng Nhật cơ bản"

[output.html]
default-theme = "Navy"
additional-css = ["style/custom.css"]
no-section-label = true
